# Generated by Django 5.0.3 on 2024-06-09 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0023_coursefile_student_view_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_view_time',
            name='file_id',
        ),
    ]
