# Generated by Django 5.0.3 on 2024-06-09 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0024_remove_student_view_time_file_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_View_Time',
        ),
    ]
