# Generated by Django 5.0.3 on 2024-06-09 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0025_delete_student_view_time'),
        ('users', '0003_alter_userinfo_email_alter_userinfo_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_View_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_time', models.IntegerField(default=0)),
                ('file_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.coursefile')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userinfo')),
            ],
        ),
    ]
